services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      file:
        .env
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      file:
        .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
